Group
omatomo/chat-space pull request #14
Opened 2017-03-04 05:49 UTC by omatomo

what
グループのモデル、コントローラの作成
グループ作成機能の実装
グループ編集機能の実装

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/groups_controller.rb
> +    @groups = Group.all
allメソッドは避けた方がいいね！全てを取り出したいんだけど、allじゃなくて降順昇順にしよう！

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/groups_controller.rb
> +   redirect_to action: 'index'
グループが作成失敗された時もflashmessageを出そう！
その際エラーの内容がグループ作成画面に出るようにしよう！

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/groups_controller.rb
> +    group_id = group.id
これは何？？？？？？？？？？？

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/groups_controller.rb
> +    flash[:notice] = "グループを変更しました。"
ここも！

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/messages_controller.rb
> +  	  flash[:alert] = "メッセージを入力してください。"
ここも！エラー内容が出るようにしよう！

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/messages_controller.rb
> +  	  message.save
成功した時のflashmessage!

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/messages_controller.rb
> +  	  redirect_to :back
good!

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/messages_controller.rb
> +  	@group = Group.find(params[:group_id])
インデント！

2017-03-07 04:59 UTC, tomoki0120 commented on app/controllers/messages_controller.rb
> +    @groups = Group.all
ここもall🙅

2017-03-07 04:59 UTC, tomoki0120 commented on app/models/group.rb
> +   accepts_nested_attributes_for :users, allow_destroy: true
validationをかけよう！

2017-03-07 04:59 UTC, tomoki0120 commented on app/views/groups/_box.html.haml
> +      =group.messages.last.try(:body) || "まだメッセージがありません。"
good!!

2017-03-07 04:59 UTC, tomoki0120 commented on app/views/groups/edit.html.haml
> +          = f.submit "Save", name: "commit", class: "chat-group-form__action-btn"
good!

2017-03-07 04:59 UTC, tomoki0120 commented on app/views/layouts/mailer.html.haml
> +    = yield
mailerは削除して生成されないようにしよう！

2017-03-07 06:47 UTC, omatomo commented on app/controllers/groups_controller.rb
> +    @groups = Group.all
done

2017-03-07 06:47 UTC, omatomo commented on app/controllers/groups_controller.rb
> +    flash[:notice] = "グループを変更しました。"
done

2017-03-07 06:52 UTC, omatomo commented on app/controllers/messages_controller.rb
> +    @groups = Group.all
done

2017-03-07 06:54 UTC, omatomo commented on app/views/layouts/mailer.html.haml
> +    = yield
done

2017-03-07 06:55 UTC, omatomo commented on app/controllers/messages_controller.rb
> +  	@group = Group.find(params[:group_id])
done

2017-03-07 06:57 UTC, omatomo commented on app/controllers/messages_controller.rb
> +  	  message.save
done

2017-03-07 10:19 UTC, omatomo commented on app/controllers/groups_controller.rb
> +    group_id = group.id
done

2017-03-07 10:31 UTC, omatomo commented on app/controllers/groups_controller.rb
> +    group_id = group.id
group_messages GET    /groups/:group_id/messages(.:format) messages#index
がredirect_to の行き先だったので
:group_idの部分はgroup_idというものに変換しなくてはいけないと勘違いしてました。
普通にgroup.idでいけました。

2017-03-08 04:25 UTC, omatomo commented on app/controllers/groups_controller.rb
> +   redirect_to action: 'index'
done

2017-03-08 04:27 UTC, omatomo commented on app/controllers/messages_controller.rb
> +  	  flash[:alert] = "メッセージを入力してください。"
done

2017-03-08 04:27 UTC, omatomo commented on app/models/group.rb
> +   accepts_nested_attributes_for :users, allow_destroy: true
done

2017-03-08 07:29 UTC, hc0208 requested changes

2017-03-08 07:29 UTC, hc070208 commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
&__errorsにしよう
他の部分もかえよう

2017-03-08 07:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +     redirect_to action: 'index'
prefixで統一しよう

2017-03-08 07:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +     redirect_to :back
prefixで統一しよう

2017-03-08 07:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +     redirect_to action: 'index'
redirect_toのオプションでflashメッセージ書こう

2017-03-08 07:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +  	group.update(group_params)
ここもsaveの時と同じように条件分岐しよう

2017-03-08 07:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +  	@group = Group.find(params[:id])
@group = Group.find(params[:id])
はeditとupdateで共通だからbefore_actionで統一すると綺麗になるよ！

2017-03-08 07:29 UTC, hc070208 commented on app/controllers/messages_controller.rb
> +  	if message.body.blank?
モデルのバリデーションに書くようにしよう

2017-03-08 07:29 UTC, hc070208 commented on app/views/groups/_box.html.haml
> +      =link_to group.group_name, group_messages_path(group.id), method: :get, :style=>"color: white; text-decoration: none;"
group_messages_path(group)だけで大丈夫

2017-03-08 07:29 UTC, hc070208 commented on app/views/groups/_box.html.haml
> +      =link_to group.group_name, group_messages_path(group.id), method: :get, :style=>"color: white; text-decoration: none;"
method: :getはいらないね。
あとなるべくstyleはcssファイルに書いた方がいいかな

2017-03-08 08:30 UTC, omatomo commented on app/assets/stylesheets/group.scss
> +  .chat-group-form__errors {
done

2017-03-08 08:30 UTC, omatomo commented on app/controllers/groups_controller.rb
> +     redirect_to action: 'index'
done

2017-03-08 08:37 UTC, omatomo commented on app/controllers/groups_controller.rb
> +     redirect_to :back
done

2017-03-08 08:37 UTC, omatomo commented on app/controllers/groups_controller.rb
> +  	@group = Group.find(params[:id])
done

2017-03-08 09:06 UTC, omatomo commented on app/controllers/groups_controller.rb
> +  	group.update(group_params)
done

2017-03-08 09:16 UTC, omatomo commented on app/controllers/messages_controller.rb
> +  	if message.body.blank?
done

2017-03-08 10:07 UTC, merged